### ISSUE TITLE
Polymer is not defined

### ISSUE THREAD

**Issue by SiddiqueAhmad** [roguePanda/aurelia-polymer#1]
i did as said in readme, but getting following error, let me know if you need more info on it

https://github.com/roguePanda/aurelia-polymer/blob/master/src/index.js#L36 this line has that undefined Polymer variable

Unhandled promise rejection ReferenceError: Polymer is not defined
    at r.configure (http://localhost:9000/jspm_packages/github/roguePanda/aurelia-polymer@0.1.0/index.js:44:25)
    at http://localhost:9000/jspm_packages/github/aurelia/framework@0.17.0/aurelia-framework.js:34:34
    at f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at Number.f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1596:24)
    at q (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1600:11)(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
shim.min.js:1444 Unhandled promise rejection ReferenceError: Polymer is not defined(…)(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600

**Comment by bnavetta** [comment]
What version of Aurelia were you using? Recent versions stopped using HTMLImport, which could be part of the problem.

**Comment by SiddiqueAhmad** [comment]
Recent version

**Comment by bnavetta** [comment]
I haven't really tested it with the new version, but that's issue #2, and I'm taking a look at if the WebComponents polyfill is needed with the latest version of Aurelia and its HTMLImport plugin.

**Comment by SiddiqueAhmad** [comment]
Okay thank you I will wait

**Comment by bnavetta** [comment]
I released a new 1.0.0-beta.2 version of the plugin a few days ago that should work with the latest Aurelia beta. Polymer needs to be loaded before Aurelia so that the plugin can hook into its registration lifecycle, which might be the problem here. I have some rough docs [here](https://gist.github.com/roguePanda/3a0854de9c71dfac3ff8) that might help as well

**Comment by k2s** [comment]
@roguePanda I think this issue should be closed
